AWSTemplateFormatVersion: "2010-09-09"
Description: "Product data information for supporters."

Parameters:
  Stage:
    Description: Stage name
    Type: String
    AllowedValues:
      - PROD
      - UAT
      - CODE
    Default: CODE

Conditions:
  CreateProdResources: !Equals [!Ref "Stage", "PROD"]

Mappings:
  StageVariables:
    CODE:
      S3Bucket: supporter-product-data-export-code
      scheduleRate: "rate(5 minutes)"
    UAT:
      S3Bucket: supporter-product-data-export-uat
      scheduleRate: "rate(10 minutes)"
    PROD:
      S3Bucket: supporter-product-data-export-prod
      scheduleRate: "rate(10 minutes)"

Resources:

  SupporterProductExportBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName:
        !FindInMap [StageVariables, !Ref Stage, S3Bucket]
      AccessControl: Private
      LifecycleConfiguration:
        Rules:
          - Id: DeleteAllOldFiles
            Prefix: ""
            Status: Enabled
            ExpirationInDays: 365
          - Id: DeleteOldFilesZuora
            Prefix: "zuora"
            Status: Enabled
            ExpirationInDays: 14
      VersioningConfiguration:
        Status: "Enabled"

  EncryptBucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn: SupporterProductExportBucket
    Properties:
      Bucket: !Sub ${SupporterProductExportBucket}
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyIncorrectEncryptionHeader
            Effect: Deny
            Principal: "*"
            Action: s3:PutObject
            Resource: !Sub arn:aws:s3:::${SupporterProductExportBucket}/*
            Condition:
              StringNotEquals:
                s3:x-amz-server-side-encryption:
                  - AES256
                  - aws:kms
          - Sid: DenyUnEncryptedObjectUploads
            Effect: Deny
            Principal: "*"
            Action: s3:PutObject
            Resource: !Sub arn:aws:s3:::${SupporterProductExportBucket}/*
            Condition:
              'Null':
                s3:x-amz-server-side-encryption: 'true'

  SupporterProductDataLambdaRole:
    Type: AWS::IAM::Role
    DependsOn: SupporterProductExportBucket
    Properties:
      RoleName: !Sub SupportProductData-${Stage}
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: LambdaPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - lambda:InvokeFunction
                Resource: "*"
        - PolicyName: PrivateBucket
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action: s3:GetObject
                Resource: !Sub arn:aws:s3:::gu-reader-revenue-private/membership/supporter-product-data/${Stage}/*
        - PolicyName: WorkBucket
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - s3:AbortMultipartUpload
                  - s3:DeleteObject
                  - s3:GetObject
                  - s3:GetObjectAcl
                  - s3:GetBucketAcl
                  - s3:ListBucket
                  - s3:PutObject
                  - s3:GetObjectVersion
                  - s3:DeleteObjectVersion
                Resource: !Sub arn:aws:s3:::${SupporterProductExportBucket}/*
        - PolicyName: ListWorkBucket
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource: !Sub arn:aws:s3:::${SupporterProductExportBucket}
        - PolicyName: SSMConfigParams
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParametersByPath
                Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/supporter-product-data/*
        - PolicyName: DynamoTable
          PolicyDocument:
            Version: 2012-10-17
            Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:GetItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
                - dynamodb:BatchGetItem
                - dynamodb:DescribeTable
              Resource:
                Fn::ImportValue:
                  !Sub supporter-product-data-tables-${Stage}-SupporterProductDataTable

  QueryZuoraLambda:
    Type: "AWS::Lambda::Function"
    Properties:
      FunctionName:
        !Sub support-SupporterProductDataQueryZuora-${Stage}
      Description: "Trigger zuora export"
      Handler: "com.gu.lambdas.QueryZuoraLambda::handleRequest"
      Role: !GetAtt [ SupporterProductDataLambdaRole, Arn ]
      Code:
        S3Bucket: supporter-product-data-dist
        S3Key: !Sub support/${Stage}/supporter-product-data/supporter-product-data.jar
      MemorySize: 512
      Runtime: "java8"
      Timeout: 300
      Environment:
        Variables:
          'Stage': !Sub ${Stage}

  FetchResultsLambda:
    Type: "AWS::Lambda::Function"
    Properties:
      FunctionName:
        !Sub support-SupporterProductDataFetchResults-${Stage}
      Description: "Fetch zuora export results"
      Handler: "com.gu.lambdas.FetchResultsLambda::handleRequest"
      Role: !GetAtt [ SupporterProductDataLambdaRole, Arn ]
      Code:
        S3Bucket: supporter-product-data-dist
        S3Key: !Sub support/${Stage}/supporter-product-data/supporter-product-data.jar
      MemorySize: 512
      Runtime: "java8"
      Timeout: 300
      Environment:
        Variables:
          'Stage': !Sub ${Stage}

  UpdateDynamoLambda:
    Type: "AWS::Lambda::Function"
    Properties:
      FunctionName:
        !Sub support-SupporterProductDataUpdateDynamo-${Stage}
      Description: "Update DynamoDB with the results of the Zuora query"
      Handler: "com.gu.lambdas.UpdateDynamoLambda::handleRequest"
      Role: !GetAtt [ SupporterProductDataLambdaRole, Arn ]
      Code:
        S3Bucket: supporter-product-data-dist
        S3Key: !Sub support/${Stage}/supporter-product-data/supporter-product-data.jar
      MemorySize: 512
      Runtime: "java8"
      Timeout: 600
      Environment:
        Variables:
          'Stage': !Sub ${Stage}

  StatesExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: "Allow"
          Principal:
            Service: !Sub states.${AWS::Region}.amazonaws.com
          Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: StatesExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "lambda:InvokeFunction"
                Resource: "*"

  SupporterProductData:
    Type: "AWS::StepFunctions::StateMachine"
    Properties:
      StateMachineName: !Sub supporter-product-data-${Stage}
      DefinitionString:
        !Sub
        - |-
          {
            "StartAt": "QueryZuora",
            "States": {
              "QueryZuora": {
                "Type": "Task",
                "Resource": "${querierArn}",
                "Next": "WaitSomeTime",
                "Retry": [
                   {
                    "ErrorEquals": ["States.ALL"],
                    "IntervalSeconds": 30,
                    "MaxAttempts": 3
                  }]
              },
              "WaitSomeTime": {
                "Type": "Wait",
                "Seconds": 30,
                "Next": "FetchResults"
              },
              "FetchResults": {
                "Type": "Task",
                "Resource": "${fetcherArn}",
                "Next": "CheckForNewSubscriptions",
                "Retry": [
                   {
                    "ErrorEquals": ["States.ALL"],
                    "IntervalSeconds": 60,
                    "MaxAttempts": 20,
                    "BackoffRate": 1.0
                  }]
              },
              "CheckForNewSubscriptions": {
                "Type": "Choice",
                "Choices": [
                  {
                      "Variable": "$.recordCount",
                      "NumericEquals": 0,
                      "Next": "NoNewSubscriptions"
                  }
                ],
                "Default": "UpdateDynamo"
              },
              "NoNewSubscriptions": {
                "Type": "Pass",
                "End": true
              },
              "UpdateDynamo": {
                "Type": "Task",
                "Resource": "${dynamoArn}",
                "Next": "CheckProcessingComplete",
                "Retry": [
                   {
                    "ErrorEquals": ["States.ALL"],
                    "IntervalSeconds": 30,
                    "MaxAttempts": 3,
                    "BackoffRate": 1.0
                  }]
              },
              "CheckProcessingComplete": {
                "Type": "Choice",
                "Choices": [
                  {
                      "Variable": "$.recordCount",
                      "NumericGreaterThanPath": "$.processedCount",
                      "Next": "UpdateDynamo"
                  }
                ],
                "Default": "ProcessingComplete"
              },
              "ProcessingComplete": {
                "Type": "Pass",
                "End": true
              }
            }
          }
        - {
          querierArn: !GetAtt [ QueryZuoraLambda, Arn ],
          fetcherArn: !GetAtt [ FetchResultsLambda, Arn ],
          dynamoArn: !GetAtt [ UpdateDynamoLambda, Arn ]
        }
      RoleArn: !GetAtt [ StatesExecutionRole, Arn ]

  SupporterProductDataScheduledRule:
    Type: "AWS::Events::Rule"
    Properties:
      Description: "Trigger regular data synchronisation from Zuora"
      ScheduleExpression: !FindInMap [StageVariables, !Ref Stage, scheduleRate]
      State: "ENABLED"
      Targets:
        -
          Arn: !Ref SupporterProductData
          Id: !Sub trigger_state_machine-${Stage}-1
          Input: |
            {
              "queryType":"incremental"
            }
          RoleArn: !GetAtt [ SupporterProductDataTriggerRole, Arn ]

  SupporterProductDataTriggerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: TriggerStateMchine
          PolicyDocument:
            Version : "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - states:StartExecution
                Resource: !Ref SupporterProductData

  SupporterProductDataAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: CreateProdResources
    Properties:
      AlarmActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:reader-revenue-dev
      AlarmName: !Join
        - ' '
        - - 'URGENT 9-5 -'
          - !Ref 'Stage'
          - 'Failed to extract supporter product data from Zuora'
      AlarmDescription: !Join
        - ' '
        - - 'Impact - members-data-api attribute data may be incorrect. Fix SupporterProductData ASAP!'
          - 'Follow the process in https://docs.google.com/document/d/1_3El3cly9d7u_jPgTcRjLxmdG2e919zCLvmcFCLOYAk/edit'
      MetricName: ExecutionsFailed
      Namespace: AWS/States
      Dimensions:
        - Name: StateMachineArn
          Value: !Ref SupporterProductData
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 1
      Period: 60
      EvaluationPeriods: 1
      Statistic: Sum
      TreatMissingData: notBreaching
    DependsOn: SupporterProductData
