AWSTemplateFormatVersion: "2010-09-09"
Description: "Product data information for supporters."

Parameters:
  Stage:
    Description: Stage name
    Type: String
    AllowedValues:
      - PROD
      - UAT
      - DEV
    Default: DEV

Conditions:
  CreateProdResources: !Equals [!Ref "Stage", "PROD"]

Mappings:

  EnvironmentBucketMap:
    CODE:
      "export": "supporter-product-export-code"
    PROD:
      "export": "supporter-product-export-prod"

  Constants:
    Alarm:
      Process: Follow the process in https://docs.google.com/document/d/1_3El3cly9d7u_jPgTcRjLxmdG2e919zCLvmcFCLOYAk/edit
      Urgent: URGENT 9-5 -

Resources:

  SupporterProductExportBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName:
        Fn::FindInMap:
          - EnvironmentBucketMap
          - Ref: Stage
          - "export"
      AccessControl: Private
      LifecycleConfiguration:
        Rules:
          - Id: DeleteAllOldFiles
            Prefix: ""
            Status: Enabled
            ExpirationInDays: 365
          - Id: DeleteOldFilesZuora
            Prefix: "zuora"
            Status: Enabled
            ExpirationInDays: 14
      VersioningConfiguration:
        Status: "Enabled"

  EncryptBucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn: SupporterProductExportBucket
    Properties:
      Bucket: !Sub ${SupporterProductExportBucket}
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyIncorrectEncryptionHeader
            Effect: Deny
            Principal: "*"
            Action: s3:PutObject
            Resource: !Sub arn:aws:s3:::${SupporterProductExportBucket}/*
            Condition:
              StringNotEquals:
                s3:x-amz-server-side-encryption:
                  - AES256
                  - aws:kms
          - Sid: DenyUnEncryptedObjectUploads
            Effect: Deny
            Principal: "*"
            Action: s3:PutObject
            Resource: !Sub arn:aws:s3:::${SupporterProductExportBucket}/*
            Condition:
              'Null':
                s3:x-amz-server-side-encryption: 'true'

  SupporterProductDataLambdaRole:
    Type: AWS::IAM::Role
    DependsOn: SupporterProductExportBucket
    Properties:
      RoleName: !Sub SupportProductData-${Stage}
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: LambdaPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - lambda:InvokeFunction
                Resource: "*"
        - PolicyName: PrivateBucket
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action: s3:GetObject
                Resource: !Sub arn:aws:s3:::gu-reader-revenue-private/membership/supporter-product-data/${Stage}/*
        - PolicyName: WorkBucket
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - s3:AbortMultipartUpload
                  - s3:DeleteObject
                  - s3:GetObject
                  - s3:GetObjectAcl
                  - s3:GetBucketAcl
                  - s3:ListBucket
                  - s3:PutObject
                  - s3:GetObjectVersion
                  - s3:DeleteObjectVersion
                Resource: !Sub arn:aws:s3:::${SupporterProductExportBucket}/*
        - PolicyName: ListWorkBucket
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource: !Sub arn:aws:s3:::${SupporterProductExportBucket}
        - PolicyName: SSMConfigParams
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParametersByPath
                Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/supporter-product-data/*

  ZuoraQuerierLambda:
    Type: "AWS::Lambda::Function"
    Properties:
      FunctionName:
        !Sub membership-SupporterProductDataQuerier-${Stage}
      Description: "Trigger zuora export"
      Handler: "com.gu.lambdas.ZuoraQuerierLambda::handleRequest"
      Role: !GetAtt [ SupporterProductDataLambdaRole, Arn ]
      Code:
        S3Bucket: supporter-product-data-dist
        S3Key: !Sub ${Stage}/supporter-product-data.jar
      MemorySize: 512
      Runtime: "java8"
      Timeout: 300
      Environment:
        Variables:
          'Stage': !Sub ${Stage}

  ResultsFetcherLambda:
    Type: "AWS::Lambda::Function"
    Properties:
      FunctionName:
        !Sub membership-SupporterProductDataFetcher-${Stage}
      Description: "Fetch zuora export results"
      Handler: "com.gu.lambdas.ZuoraResultsFetcherLambda::handleRequest"
      Role: !GetAtt [ SupporterProductDataLambdaRole, Arn ]
      Code:
        S3Bucket: supporter-product-data-dist
        S3Key: !Sub ${Stage}/supporter-product-data.jar
      MemorySize: 512
      Runtime: "java8"
      Timeout: 300
      Environment:
        Variables:
          'Stage': !Sub ${Stage}

  StatesExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: "Allow"
          Principal:
            Service: !Sub states.${AWS::Region}.amazonaws.com
          Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: StatesExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "lambda:InvokeFunction"
                Resource: "*"

  SupporterProductDataCODE:
    Type: "AWS::StepFunctions::StateMachine"
    Properties:
      StateMachineName: supporter-product-data-UAT
      DefinitionString:
        !Sub
        - |-
          {
            "StartAt": "QueryZuora",
            "States": {
              "QueryZuora": {
                "Type": "Task",
                "Resource": "${querierArn}",
                "Next": "WaitSomeTime",
                "Retry": [
                   {
                    "ErrorEquals": ["States.ALL"],
                    "IntervalSeconds": 30,
                    "MaxAttempts": 3
                  }]
              },
              "WaitSomeTime": {
                "Type": "Wait",
                "Seconds": 60,
                "Next": "FetchResults"
              },
              "FetchResults": {
                "Type": "Task",
                "Resource": "${fetcherArn}",
                "End": true,
                "Retry": [
                   {
                    "ErrorEquals": ["States.ALL"],
                    "IntervalSeconds": 60,
                    "MaxAttempts": 20,
                    "BackoffRate": 1.0
                  }]
              }
            }
          }
        - {
          querierArn: !GetAtt [ ZuoraQuerierLambda, Arn ],
          fetcherArn: !GetAtt [ ResultsFetcherLambda, Arn ]
        }
      RoleArn: !GetAtt [ StatesExecutionRole, Arn ]

  SupporterProductDataUAT:
    Type: "AWS::StepFunctions::StateMachine"
    Properties:
      StateMachineName: supporter-product-data-UAT
      DefinitionString:
        !Sub
        - |-
          {
            "StartAt": "QueryZuora",
            "States": {
              "QueryZuora": {
                "Type": "Task",
                "Resource": "${querierArn}",
                "Next": "WaitSomeTime",
                "Retry": [
                   {
                    "ErrorEquals": ["States.ALL"],
                    "IntervalSeconds": 30,
                    "MaxAttempts": 3
                  }]
              },
              "WaitSomeTime": {
                "Type": "Wait",
                "Seconds": 180,
                "Next": "FetchResults"
              },
              "FetchResults": {
                "Type": "Task",
                "Resource": "${fetcherArn}",
                "End": true,
                "Retry": [
                   {
                    "ErrorEquals": ["States.ALL"],
                    "IntervalSeconds": 60,
                    "MaxAttempts": 20,
                    "BackoffRate": 1.0
                  }]
              }
            }
          }
        - {
          querierArn: !GetAtt [ ZuoraQuerierLambda, Arn ],
          fetcherArn: !GetAtt [ ResultsFetcherLambda, Arn ]
        }
      RoleArn: !GetAtt [ StatesExecutionRole, Arn ]

  SupporterProductDataPROD:
    Type: "AWS::StepFunctions::StateMachine"
    Properties:
      StateMachineName: supporter-product-data-PROD
      DefinitionString:
        !Sub
        - |-
          {
            "StartAt": "QueryZuora",
            "States": {
              "QueryZuora": {
                "Type": "Task",
                "Resource": "${querierArn}",
                "Next": "WaitSomeTime",
                "Retry": [
                   {
                    "ErrorEquals": ["States.ALL"],
                    "IntervalSeconds": 30,
                    "MaxAttempts": 3
                  }]
              },
              "WaitSomeTime": {
                "Type": "Wait",
                "Seconds": 180,
                "Next": "FetchResults"
              },
              "FetchResults": {
                "Type": "Task",
                "Resource": "${fetcherArn}",
                "End": true,
                "Retry": [
                   {
                    "ErrorEquals": ["States.ALL"],
                    "IntervalSeconds": 60,
                    "MaxAttempts": 20,
                    "BackoffRate": 1.0
                  }]
              }
            }
          }
        - {
          querierArn: !GetAtt [ ZuoraQuerierLambda, Arn ],
          fetcherArn: !GetAtt [ ResultsFetcherLambda, Arn ]
        }
      RoleArn: !GetAtt [ StatesExecutionRole, Arn ]

  SupporterProductDataScheduledRule:
    Type: "AWS::Events::Rule"
    Properties:
      Description: "Trigger nightly data synchronisation"
      ScheduleExpression: "cron(00 3 ? * * *)"
      State: "ENABLED"
      Targets:
        -
          Arn: !Ref SupporterProductDataPROD
          Id: !Sub trigger_state_machine-${Stage}-1
          Input: |
            {
            "foo":"bar"
            }
          RoleArn: !GetAtt [ SupporterProductDataTriggerRole, Arn ]

  SupporterProductDataTriggerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: TriggerStateMchine
          PolicyDocument:
            Version : "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - states:StartExecution
                Resource: !Ref SupporterProductDataPROD

  SupporterProductDataAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: CreateProdResources
    Properties:
      AlarmActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:reader-revenue-dev
      AlarmName: !Join
        - ' '
        - - !FindInMap [ Constants, Alarm, Urgent ]
          - !Ref 'Stage'
          - 'Failed to extract supporter product data from Zuora'
      AlarmDescription: !Join
        - ' '
        - - 'Impact - members-data-api attribute data may be incorrect. Fix SupporterProductData ASAP!'
          - !FindInMap [ Constants, Alarm, Process ]
      MetricName: ExecutionsFailed
      Namespace: AWS/States
      Dimensions:
        - Name: StateMachineArn
          Value: !Ref SupporterProductDataPROD
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 1
      Period: 60
      EvaluationPeriods: 1
      Statistic: Sum
      TreatMissingData: notBreaching
    DependsOn: SupporterProductDataPROD
