AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Stack:
    Description: Stack name
    Type: String
    Default: support
  App:
    Description: Application name
    Type: String
    Default: support-logs-retention-lambda
  Stage:
    Description: Stage name
    Type: String
    Default: PROD
  DeployBucket:
    Description: Bucket where RiffRaff uploads artifacts on deploy
    Type: String
    Default: subscriptions-dist
  VpcId:
    Description: Vpc where the lambda is being created
    Type: AWS::EC2::VPC::Id
    Default: vpc-e6e00183

Resources:
  RetentionLambdaSecurityGroup:
   Type: AWS::EC2::SecurityGroup
   Properties:
     GroupDescription: !Sub Security group for the ${App}-${Stage} lambda
     VpcId: !Ref VpcId
     SecurityGroupEgress:
     - IpProtocol: tcp
       FromPort: 433
       ToPort: 443
       SourceSecurityGroupId: sg-05c221879675c1e45
  RetentionLambda:
   Type: AWS::Serverless::Function
   Properties:
     FunctionName: !Sub ${App}-${Stage}
     Description: Deletes old indices from support-logs.gutools.co.uk
     Events:
       Timer:
        Type: Schedule
        Properties:
          Description: Delete old indices daily at 10
          Schedule: cron(0 10 * * ? *)
     Runtime: python3.6
     Handler: lambda_function.lambda_handler
     MemorySize: 128
     Timeout: 30
     CodeUri:
       Bucket: !Ref DeployBucket
       Key: !Sub ${Stack}/${Stage}/${App}/${App}.zip
     VpcConfig:
       SecurityGroupIds:
         - !Ref RetentionLambdaSecurityGroup
       SubnetIds: 
         - subnet-0d6f657eea1baf777
         - subnet-087346aaeef11b924
     Tags:
       App: !Ref App
       Stack: !Ref Stack
       Stage: !Ref Stage
     Policies:
       - Version: '2012-10-17'
         Statement:
           - Effect: Allow
             Action:
               - es:ESHttpPost
               - es:ESHttpGet
               - es:ESHttpPut 
               - es:ESHttpDelete 
             Resource: arn:aws:es:eu-west-1:865473395570:domain/support-elk-domain*
       - Version: '2012-10-17'
         Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
                - ec2:CreateNetworkInterface
                - ec2:DescribeNetworkInterfaces
                - ec2:DeleteNetworkInterface
              Resource: "*"
